import Head from 'next/head'
import Image from 'next/image'
import styles from './layout.module.css'

import Nav from '../components/nav'
// error-handling
// console.log(wa)

export default function Layout({children}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>My site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Nav />
      </header>

      <main className={styles.main}>
        {children}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2021
        </a>
      </footer>
    </div>
  )
}
