import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// error-handling
// console.log(wa)

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my blog
        </h1>

        <p className={styles.description}>
          This is my blog. Read my stuff.
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright 2021
        </a>
      </footer>
    </div>
  )
}
